# Generated by Django 5.0.2 on 2024-03-07 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubTipoMatPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMatPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(choices=[('M', 'Metro'), ('P', 'Peça')], max_length=1)),
                ('largura', models.IntegerField(blank=True, null=True)),
                ('data_atualizacao_preco', models.DateField(default=django.utils.timezone.now)),
                ('subtipo_matprima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='matprima.subtipomatprima')),
            ],
        ),
        migrations.CreateModel(
            name='MatPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo_matprima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_matprimas', to='matprima.tipomatprima')),
            ],
        ),
    ]
