# Generated by Django 5.0.2 on 2024-03-10 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matprima', '0001_initial'),
        ('molde', '0001_initial'),
        ('produto', '0002_rename_descricao_produto_tipomatprima_nome_moldeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoVariavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_variavel', models.CharField(max_length=100)),
                ('imagem_variavel', models.ImageField(upload_to='imagens_variavel/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoVariavelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('matprima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matprima.matprima')),
                ('molde_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molde.moldeitem')),
                ('produto_variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto_variavel.produtovariavel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
