# Generated by Django 5.0.2 on 2024-03-12 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto_variavel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtovariavelitem',
            name='produto_variavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_produto_variavel', to='produto_variavel.produtovariavel'),
        ),
    ]
