# Generated by Django 5.0.2 on 2024-03-07 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matprima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_molde', models.CharField(max_length=50)),
                ('imagem_molde', models.ImageField(blank=True, null=True, upload_to='imagens_moldes/')),
            ],
        ),
        migrations.CreateModel(
            name='MoldeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('quantidade_x', models.IntegerField(default=1)),
                ('altura', models.IntegerField(blank=True, default=0, null=True)),
                ('largura', models.IntegerField(blank=True, default=0, null=True)),
                ('quantidade', models.IntegerField()),
                ('molde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='molde.molde')),
                ('subtipo_matprima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matprima.subtipomatprima')),
            ],
        ),
    ]
