# Generated by Django 5.0.2 on 2024-03-07 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matprima', '0001_initial'),
        ('molde', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem_produto', models.ImageField(blank=True, null=True, upload_to='imagens_produtos/')),
                ('molde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molde.molde')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Produto_TipoMatPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=0)),
                ('molde_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molde.moldeitem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
                ('tipo_matprima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matprima.tipomatprima')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='tipos_materia_prima',
            field=models.ManyToManyField(related_name='produtos', through='produto.Produto_TipoMatPrima', to='matprima.tipomatprima'),
        ),
    ]
