# Generated by Django 5.0.2 on 2024-03-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto_tipomatprima',
            old_name='descricao',
            new_name='nome_moldeitem',
        ),
    ]
