# Generated by Django 5.0.2 on 2024-03-12 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto_variavel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('data_fechamento', models.DateField(auto_now=True)),
                ('descricao', models.CharField(max_length=100)),
                ('status', models.CharField(default='Aberto', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServicoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordem_servico.ordemservico')),
                ('produto_variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto_variavel.produtovariavel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
